project_id = "vf-kim-son-trang-dai"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.migrations]
enabled = true

[db.seed]
enabled = false

[auth]
enabled = true
site_url = "https://ordermanagement-three.vercel.app/"
additional_redirect_urls = [
  "https://ordermanagement-three.vercel.app",
  "https://ordermanagement-three.vercel.app/login",
  "https://ordermanagement-three.vercel.app/set-password",
  "http://127.0.0.1:3000",
  "http://localhost:3000",
  "http://127.0.0.1:3000/set-password",
  "http://localhost:3000/set-password"
]

[functions.run-sql]
enabled = true
verify_jwt = true
import_map = "./functions/run-sql/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/run-sql/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/run-sql/*.html" ]
